### ISSUE TITLE
Issues with running

### ISSUE THREAD

**Issue by W00glin** [Th3J0kr/jtb_investigator#2]
Sup,

I cloned the repo to my machine. Changed into the directories and then ran the pip install -r requirements.txt eveything looks good. I go to use the tool and I am hit with the error:

`Traceback (most recent call last):
  File "./jtb.py", line 4, in <module>
    from investigation import Investigate, Host
  File "/opt/jtb_investigator/investigation.py", line 1, in <module>
    from modules import Lookup, PortScan, Whois, AsnLookup, UtcToLocal, BlackListCheck
  File "/opt/jtb_investigator/modules.py", line 3, in <module>
    import nmap
ModuleNotFoundError: No module named 'nmap'`

NMAP is currently installed an operational on the machine. Any advice?

**Comment by Th3J0kr** [comment]
run pip3 install -r requirements or pip3 install python-nmap.

**Comment by W00glin** [comment]
> 
> 
> run pip3 install -r requirements or pip3 install python-nmap.

Reran those. Some dependencies got missed. Odd.
